name: Daily Checkout Cleanup

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:      # Also allow manual run

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Run SQL to clean checkout_sessions
        uses: tj-actions/pg-sql@v5
        with:
          postgresql_connection_string: ${{ secrets.DATABASE_URL }}
          sql: |
            DELETE FROM checkout_sessions
            WHERE created_at < NOW() - INTERVAL '1 day';